sudo: required
language: node-js

install: "npm install"
script: "npm run dist"
os: linux
dist: trusty
language: node-js
node-js: "9"

before_install:
  - nvm install 9
  - node -v
  - npm -v
