sudo: required
language: node-js

install: "npm install"
script: "npm run dist"

matrix:
  include:
    - os: linux
      dist: trusty
      node-js: "8"
      sudo: required
    - os: osx
      osx_image: xcode7.2
      node-js: "8"

before_install:
  -node -v
cache:
  directories:
  - $HOME/.yarn-cache
