version: 0.0.1.{build}
platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

install:
  - ps: Install-Product node 9 x64
  - yarn

build_script:
  - yarn dist

test: off

deploy:
  - provider: GitHub
    auth_token:
      secure: ZIWtA/LeJgmNgq0Q8KGZjII3GsbXzLLOu/g6TVQ3T7Ry+CleVnHjDukulvDGZ+us
    on:
      branch: master
      appveyor_repo_tag: true