version: 0.0.2.{build}
platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

install:
  - ps: Install-Product node 9 x64
  - yarn

build_script:
  - yarn dist

test: off

artifacts:
  - path: '.\dist\mako Setup 0.0.2.exe'
    name: Setup

deploy:
  - provider: GitHub
    auth_token:
      secure: ZIWtA/LeJgmNgq0Q8KGZjII3GsbXzLLOu/g6TVQ3T7Ry+CleVnHjDukulvDGZ+us
    artifacts: Setup
    on:
      branch: v0.0.2
      appveyor_repo_tag: true
