version: 0.0.1.{build}
platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

install:
  - ps: Install-Product node 9 x64
  - yarn

build_script:
  - yarn dist

test: off