version: 0.1.1.{build}
platform:
  - x32
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

install:
  - ps: Install-Product node 8
  - yarn

build_script:
  - yarn dist

test: on

#artifacts:
#  - path: '.\dist\*.exe'
#    name: Setup

deploy:
  - provider: GitHub
    auth_token:
      secure: ZIWtA/LeJgmNgq0Q8KGZjII3GsbXzLLOu/g6TVQ3T7Ry+CleVnHjDukulvDGZ+us
    #artifacts: Setup
    on:
      branch: v0.1.1
      appveyor_repo_tag: true
